### ISSUE TITLE
Exceptions when download APKs

### ISSUE THREAD

**Issue by sunxiaobiu** [E0HYL/AndrozooDownloader#1]
I encountered the following exception when download APKs, do u have any advice to solve?
```
(env4native) webrtc@NSCLabHCI:~/androozooAPK/AndrozooDownloader$ python main.py 2020 --vt_detection 1 --upper 10000 --fix True --output /home/webrtc/androozooAPK/AndrozooDownloader/data
[AndrozooDownloader] Malware Samples (1<=vt_detection<10000).
[AndrozooDownloader] Selecting from markets:  ['play.google.com', 'anzhi', 'appchina']
Traceback (most recent call last):
  File "/home/webrtc/anaconda3/envs/env4native/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4554, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 157, in <module>
    meta = meta[~meta.sha256.isin(df[0].to_list())]
  File "/home/webrtc/anaconda3/envs/env4native/lib/python3.7/site-packages/pandas/core/frame.py", line 3024, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/webrtc/anaconda3/envs/env4native/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3082, in get_loc
    raise KeyError(key) from err
KeyError: 0

```

**Comment by E0HYL** [comment]
Sorry for the delay.
There's no need to use option `fix` if you run the command for the first time, cause no recorded `.csv` files for the specified year are in the working directory.
